# Generated by Django 2.2.5 on 2021-02-14 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='plan_document',
            field=models.FileField(default='aaa', upload_to='plan/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articles',
            name='text',
            field=models.TextField(error_messages={'required': '入力必須です'}),
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(error_messages={'required': '入力必須です'}, max_length=200),
        ),
    ]
